### ISSUE TITLE
when i build the game was white

### ISSUE THREAD

**Issue by 8-python-snhk** [randomguy3725/LiquidbouncePlus-Reborn#8]
when i build the game was white
![image](https://user-images.githubusercontent.com/69177759/200767488-1b292684-e2d6-4902-8541-b1a66bc58f80.png)

**Comment by 8-python-snhk** [comment]
how can i do to install optifine in build

**Comment by 8-python-snhk** [comment]
pls update the code

**Comment by 8-python-snhk** [comment]
1 and 3 all tried

**Comment by 8-python-snhk** [comment]
but idk how to do 2

**Comment by randomguy3725** [comment]
u are running client in intellij?

**Comment by 8-python-snhk** [comment]
yep

**Comment by 8-python-snhk** [comment]
My build steps are all correct

**Comment by 8-python-snhk** [comment]
but it's in white

**Comment by randomguy3725** [comment]
launch with forge or

**Comment by randomguy3725** [comment]
> but it's in white

look at ur run folder

**Comment by 8-python-snhk** [comment]
ok

**Comment by 8-python-snhk** [comment]
and?

**Comment by 8-python-snhk** [comment]
![image](https://user-images.githubusercontent.com/69177759/200810735-24a3fc43-f3e0-4f54-bbc3-250b56d7af4c.png)

**Comment by randomguy3725** [comment]
mods

**Comment by randomguy3725** [comment]
then install optifine

**Comment by 8-python-snhk** [comment]
i give it a try

**Comment by 8-python-snhk** [comment]
no was error

**Comment by 8-python-snhk** [comment]
error

**Comment by 8-python-snhk** [comment]
ava.lang.NoClassDefFoundError: bnk
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2611)
	at java.lang.Class.getField0(Class.java:3003)
	at java.lang.Class.getField(Class.java:1729)
	at net.minecraftforge.fml.client.FMLClientHandler.detectOptifine(FMLClientHandler.java:277)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:191)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:417)
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)
Caused by: java.lang.ClassNotFoundException: bnk
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 21 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 23 more

**Comment by randomguy3725** [comment]
white screen?

**Comment by randomguy3725** [comment]
give me ur discord.i send you optifine

**Comment by 8-python-snhk** [comment]
no i cant run it

**Comment by 8-python-snhk** [comment]
i cant run it

**Comment by 8-python-snhk** [comment]
when i add optinfine

**Comment by 8-python-snhk** [comment]
my optinfine in 1.8.9forge can work

**Comment by randomguy3725** [comment]
i think u install optifine wrong

**Comment by randomguy3725** [comment]
https://optifine.net/adloadx?f=OptiFine_1.8.9_HD_U_L5.jar&x=f0ee

**Comment by randomguy3725** [comment]
download

**Comment by randomguy3725** [comment]
open the jar

**Comment by 8-python-snhk** [comment]
yes i was do that

**Comment by randomguy3725** [comment]
give me ur discord

**Comment by randomguy3725** [comment]
try to launch with forge

**Comment by 8-python-snhk** [comment]
i can do that

**Comment by 8-python-snhk** [comment]
but i use lb+ r

**Comment by 8-python-snhk** [comment]
it's error

**Comment by randomguy3725** [comment]
launch with forge

**Comment by 8-python-snhk** [comment]
ok i try

**Comment by 8-python-snhk** [comment]
and can i skid this mod :) ?

**Comment by 8-python-snhk** [comment]
in next time i will try it i dont have time now

**Comment by 8-python-snhk** [comment]
thx for your help

**Comment by randomguy3725** [comment]
> and can i skid this mod :) ?

bruh

**Comment by 8-python-snhk** [comment]
in the next time i try
